### WEBHOOK_INIT
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=WEBHOOK_INIT
Content-Type: application/json

### 최초결제
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=INITIAL_PURCHASE
Content-Type: application/json


### RENEWAL
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=RENEWAL
Content-Type: application/json

### CANCELLATION_BILLING_ERROR_AFTER_EXPIRED
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=CANCELLATION_BILLING_ERROR_AFTER_EXPIRED
Content-Type: application/json



### CANCELLATION_NORMAL
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=CANCELLATION_NORMAL
Content-Type: application/json

### CANCELLATION_REFUND
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=CANCELLATION_REFUND
Content-Type: application/json

### EXPIRATION_REFUND
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=EXPIRATION_REFUND
Content-Type: application/json

### UNCANCELLATION_NORMAL
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=UNCANCELLATION_NORMAL
Content-Type: application/json

### SUBSCRIPTION_PAUSE
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=SUBSCRIPTION_PAUSED
Content-Type: application/json

### SUBSCRIPTION_EXTENDED
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=SUBSCRIPTION_EXTENDED
Content-Type: application/json

### REFUND_REVERSED
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=REFUND_REVERSED
Content-Type: application/json

### TRANSFER
POST {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/webhook?testname=TRANSFER
Content-Type: application/json

### RESET_INIT
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_INIT
Content-Type: application/json

### RESET_FREE_SKIP : 사용량이 초과되었고, 한달 뒤에 초기화가 도래하는 무료 사용자는 아무것도 하지 않는다. 
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_FREE_SKIP
Content-Type: application/json

### RESET_FREE_PROCESSED : 사용량이 초과되었고, 어제 초기화 주기가 도래했기 때문에 초기화되어야 하는 무료 사용자. 동시에 권한이 만료된 사용자. 는 초기화 주기가 한달 뒤로 변경되고, 사용량은 0이 되고, 사용가능 상태가 되야한다. 
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_FREE_PROCESSED
Content-Type: application/json

### RESET_FREE_BUT_SUBSCRIPTION_USER : 사용량이 초과 되었고, 초기화 주기가 도래한 사용자인데, RC에서는 유료 사용자라면, 유로 사용자로 전환되야 한다. (한시간 뒤에 webhook이 도착해서 무료 사용자로 초기화 될 것이다)
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_FREE_BUT_SUBSCRIPTION_USER
Content-Type: application/json


### RESET_SUB_MONTHLY_SKIP : 사용량이 초과되었고, 15일 뒤에 초기화가 도래하는 유료 사용자는 아무것도 하지 않는다. 
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_SUB_MONTHLY_SKIP
Content-Type: application/json

### RESET_SUB_MONTHLY_PROCESSED : 사용량이 초과되었고, 어제 초기화 주기가 도래했기 때문에 초기화되어야 하는 유료 사용자. 동시에 RC에서 유료 권한이 살아있는 사용자. 는 초기화 주기가 한달 뒤로 변경되고, 사용량은 0이 되고, 사용가능 상태가 되야한다. 
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_SUB_MONTHLY_PROCESSED
Content-Type: application/json


### RESET_SUB_MONTHLY_RENEWAL_FAIL : 유료 사용자가 결제에 실패해서 만료 되었을 때, 하지만 RC에서는 유료 사용자 권한이 존재하는 경우. 유료사용자로 초기화 되어야 한다.  
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/usage/reset?testname=RESET_SUB_MONTHLY_RENEWAL_FAIL
Content-Type: application/json


### embedding-scheduler
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/ai/embedding-scheduler

### 라마인더 갱신 (100개의 알람 처리)
# next_alarm_time 이 13시간 전 - 발송안함, 11시간 전 - 발송함, 1시간 후 - 발송함.
# processed_at의 값을 null로 저정해야 테스트가 됨
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/reminder/renew-alarms?fetch_limit=100
Content-Type: application/json

### 리마인더 갱신 (100개, 5초 뒤에 실행)
GET {{$dotenv NEXT_PUBLIC_HOST}}/api/reminder/renew-alarms?fetch_limit=100&delay_seconds=5
Content-Type: application/json
