name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature!
              Please fill out the form below to help us understand your idea.

    - type: textarea
      id: description
      attributes:
          label: Feature Description
          description: A clear and concise description of the feature you'd like to see.
          placeholder: Describe the feature...
      validations:
          required: true

    - type: textarea
      id: use-case
      attributes:
          label: Use Case
          description: Describe the problem you're trying to solve or the use case for this feature.
          placeholder: |
              As a user, I want to...
              So that I can...
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Have you considered any alternative solutions or workarounds?
          placeholder: Describe any alternatives you've considered...
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context, mockups, or screenshots about the feature request here.
          placeholder: Any additional information...
      validations:
          required: false
