/**
 * @jest-environment jsdom
 *
 * 제목 자동 생성 기능 테스트
 *
 * TDD Red-Green-Refactor 사이클:
 * 1. RED: 이 테스트를 먼저 작성 (실패)
 * 2. GREEN: PageEditor.tsx 구현 (통과)
 * 3. REFACTOR: 필요시 리팩토링
 */

import { describe, it, expect, jest, beforeEach } from '@jest/globals';

// Mock modules
jest.mock('@/functions/ai', () => ({
    fetchTitling: jest.fn(),
}));

describe('제목 자동 생성 기능', () => {
    let mockFetchTitling: jest.MockedFunction<any>;

    beforeEach(() => {
        jest.clearAllMocks();
        mockFetchTitling = require('@/functions/ai').fetchTitling;
    });

    describe('조건 검증', () => {
        it('본문이 100글자 이상이고 제목이 비어있으면 AI 제목 생성을 시도해야 함', async () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';

            mockFetchTitling.mockResolvedValue({
                data: { createdTitle: 'AI가 생성한 제목' },
            });

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                false, // hasAutoGeneratedTitle
                false, // isTitleLoading
                0, // lastTitleGenerationAttempt
                null, // titleGeneratedForPageRef
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(true);
        });

        it('본문이 100글자 미만이면 AI 제목 생성을 하지 않아야 함', () => {
            // Arrange
            const shortBody = 'a'.repeat(99);
            const emptyTitle = '';

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                shortBody,
                false,
                false,
                0,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });

        it('제목이 이미 있으면 AI 제목 생성을 하지 않아야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const existingTitle = '기존 제목';

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                existingTitle,
                longBody,
                false,
                false,
                0,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });

        it('이미 자동 생성된 제목이 있으면 다시 생성하지 않아야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                true, // hasAutoGeneratedTitle
                false,
                0,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });

        it('제목 로딩 중이면 생성을 시도하지 않아야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                false,
                true, // isTitleLoading
                0,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });

        it('쿨다운 기간(30초) 내에는 재시도하지 않아야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';
            const now = Date.now();
            const lastAttempt = now - 20000; // 20초 전

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                false,
                false,
                lastAttempt,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });

        it('쿨다운 기간(30초) 경과 후에는 재시도할 수 있어야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';
            const now = Date.now();
            const lastAttempt = now - 31000; // 31초 전

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                false,
                false,
                lastAttempt,
                null,
                'page-id'
            );

            // Assert
            expect(shouldGenerateTitle).toBe(true);
        });

        it('같은 페이지에서 이미 제목을 생성했으면 재생성하지 않아야 함', () => {
            // Arrange
            const longBody = 'a'.repeat(101);
            const emptyTitle = '';

            // Act
            const shouldGenerateTitle = shouldTriggerAITitleGeneration(
                emptyTitle,
                longBody,
                false,
                false,
                0,
                'page-id', // titleGeneratedForPageRef
                'page-id' // currentPageId
            );

            // Assert
            expect(shouldGenerateTitle).toBe(false);
        });
    });

    describe('제목 생성 로직', () => {
        it('AI 제목 생성 성공 시 생성된 제목을 반환해야 함', async () => {
            // Arrange
            mockFetchTitling.mockResolvedValue({
                data: { createdTitle: 'AI가 생성한 멋진 제목' },
            });

            // Act
            const result = await generateTitle('page-id', 'a'.repeat(101));

            // Assert
            expect(mockFetchTitling).toHaveBeenCalledWith('page-id', 'a'.repeat(101));
            expect(result).toBe('AI가 생성한 멋진 제목');
        });

        it('AI 제목 생성 실패 시 null을 반환해야 함', async () => {
            // Arrange
            mockFetchTitling.mockResolvedValue({
                data: { createdTitle: null },
            });

            // Act
            const result = await generateTitle('page-id', 'a'.repeat(101));

            // Assert
            expect(result).toBe(null);
        });

        it('AI 제목 생성 에러 시 에러를 throw해야 함', async () => {
            // Arrange
            const error = new Error('API Error');
            mockFetchTitling.mockRejectedValue(error);

            // Act & Assert
            await expect(generateTitle('page-id', 'a'.repeat(101))).rejects.toThrow('API Error');
        });

        it('사용량 초과 에러 시 isQuotaExceeded 플래그가 있어야 함', async () => {
            // Arrange
            const quotaError: any = new Error('월간 AI 사용량이 초과되었습니다.');
            quotaError.isQuotaExceeded = true;
            quotaError.message = '월간 AI 사용량이 초과되었습니다.';
            mockFetchTitling.mockRejectedValue(quotaError);

            // Act & Assert
            try {
                await generateTitle('page-id', 'a'.repeat(101));
            } catch (error: any) {
                expect(error.isQuotaExceeded).toBe(true);
                expect(error.message).toContain('월간 AI 사용량이 초과되었습니다');
            }
        });
    });

    describe('Fallback 제목 생성', () => {
        it('본문이 100글자 미만이면 첫 20글자를 제목으로 사용해야 함', () => {
            // Arrange
            const body = 'This is a short body with less than 100 characters.';

            // Act
            const title = generateFallbackTitle(body);

            // Assert
            expect(title).toBe('This is a short body');
            expect(title.length).toBe(20);
        });

        it('본문이 20글자 미만이면 전체를 제목으로 사용해야 함', () => {
            // Arrange
            const body = 'Short text';

            // Act
            const title = generateFallbackTitle(body);

            // Assert
            expect(title).toBe('Short text');
        });

        it('본문이 비어있으면 "제목 없음"을 반환해야 함', () => {
            // Arrange
            const body = '';

            // Act
            const title = generateFallbackTitle(body);

            // Assert
            expect(title).toBe('제목 없음');
        });

        it('HTML 태그가 포함된 본문에서 순수 텍스트만 추출해야 함', () => {
            // Arrange
            const body = '<p>Hello <strong>World</strong></p>';

            // Act
            const plainText = extractPlainText(body);
            const title = generateFallbackTitle(plainText);

            // Assert
            expect(plainText).toBe('Hello World');
            expect(title).toBe('Hello World');
        });
    });
});

// ============================================================
// 테스트용 유틸리티 함수들
// (실제 구현은 PageEditor.tsx에서 이루어짐)
// ============================================================

/**
 * AI 제목 생성을 트리거해야 하는지 판단
 */
function shouldTriggerAITitleGeneration(
    title: string,
    plainText: string,
    hasAutoGeneratedTitle: boolean,
    isTitleLoading: boolean,
    lastTitleGenerationAttempt: number,
    titleGeneratedForPageRef: string | null,
    currentPageId: string
): boolean {
    const now = Date.now();
    const cooldownPeriod = 30000; // 30초
    const isInCooldown =
        lastTitleGenerationAttempt > 0 && now - lastTitleGenerationAttempt < cooldownPeriod;

    return (
        plainText.length >= 100 &&
        (!title || title.trim() === '') &&
        !hasAutoGeneratedTitle &&
        !isTitleLoading &&
        !isInCooldown &&
        titleGeneratedForPageRef !== currentPageId
    );
}

/**
 * AI를 사용하여 제목 생성
 */
async function generateTitle(pageId: string, body: string): Promise<string | null> {
    const { fetchTitling } = require('@/functions/ai');

    const result = await fetchTitling(pageId, body);
    return result.data.createdTitle;
}

/**
 * Fallback 제목 생성 (본문 첫 20글자)
 */
function generateFallbackTitle(plainText: string): string {
    if (!plainText || plainText.trim() === '') {
        return '제목 없음';
    }
    return plainText.substring(0, 20);
}

/**
 * HTML에서 순수 텍스트 추출
 */
function extractPlainText(htmlBody: string): string {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlBody, 'text/html');
    return (doc.body.textContent || '').trim();
}
